# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(max_length=100, verbose_name='轮播图片链接'),
        ),
    ]
