# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180811_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
    ]
